CREATE DATABASE IF NOT EXISTS happytweet
	CHARACTER SET utf8 collate utf8_turkish_ci;
USE happytweet;

CREATE TABLE IF NOT EXISTS Users(
UserID bigint NOT NULL PRIMARY KEY,
AuthToken varchar(255) NOT NULL,
AuthSecret varchar(255) NOT NULL,
ScreenName varchar(255) NOT NULL,
WeeklyPoint int DEFAULT 0 NOT NULL,
TotalPoint int DEFAULT 0 NOT NULL,
CreatedOn datetime NOT NULL,
LastSync datetime DEFAULT '0000-00-00' NOT NULL,
LastSyncID bigint DEFAULT 0 NOT NULL
)CHARACTER SET utf8 collate utf8_turkish_ci;

CREATE TABLE IF NOT EXISTS Tweets(
TweetID bigint NOT NULL PRIMARY KEY,
UserID bigint NOT NULL,
TweetText varchar(255) NOT NULL,
TweetTime datetime NOT NULL,
CreatedOn datetime NOT NULL,
TotalVote bigint DEFAULT 0 NOT NULL,
VoteCount int DEFAULT 0 NOT NULL,
FOREIGN KEY (UserID)
	REFERENCES Users(UserID)
	ON UPDATE CASCADE
)CHARACTER SET utf8 collate utf8_turkish_ci;

CREATE TABLE IF NOT EXISTS Sets(
SetID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
Tweet1 bigint NOT NULL,
Tweet2 bigint NOT NULL,
Tweet3 bigint NOT NULL,
Tweet4 bigint NOT NULL,
Tweet5 bigint NOT NULL,
Tweet6 bigint NOT NULL,
Tweet7 bigint NOT NULL,
Tweet8 bigint NOT NULL,
Tweet9 bigint NOT NULL,
Tweet10 bigint NOT NULL,
CreatedOn DATETIME NOT NULL,
FOREIGN KEY(Tweet1)
	REFERENCES Tweets(TweetID)
	ON UPDATE CASCADE,
FOREIGN KEY(Tweet2)
	REFERENCES Tweets(TweetID)
	ON UPDATE CASCADE,
FOREIGN KEY(Tweet3)
	REFERENCES Tweets(TweetID)
	ON UPDATE CASCADE,
FOREIGN KEY(Tweet4)
	REFERENCES Tweets(TweetID)
	ON UPDATE CASCADE,
FOREIGN KEY(Tweet5)
	REFERENCES Tweets(TweetID)
	ON UPDATE CASCADE,
FOREIGN KEY(Tweet6)
	REFERENCES Tweets(TweetID)
	ON UPDATE CASCADE,
FOREIGN KEY(Tweet7)
	REFERENCES Tweets(TweetID)
	ON UPDATE CASCADE,
FOREIGN KEY(Tweet8)
	REFERENCES Tweets(TweetID)
	ON UPDATE CASCADE,
FOREIGN KEY(Tweet9)
	REFERENCES Tweets(TweetID)
	ON UPDATE CASCADE,
FOREIGN KEY(Tweet10)
	REFERENCES Tweets(TweetID)
	ON UPDATE CASCADE
)CHARACTER SET utf8 collate utf8_turkish_ci;


CREATE TABLE IF NOT EXISTS Words(
WordID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY ,
WordText varchar(255) NOT NULL,
Vote1Count tinyint DEFAULT 0 NOT NULL,
Vote2Count tinyint DEFAULT 0 NOT NULL,
Vote3Count tinyint DEFAULT 0 NOT NULL,
Vote4Count tinyint DEFAULT 0 NOT NULL,
Vote5Count tinyint DEFAULT 0 NOT NULL,
CreatedOn DATETIME NOT NULL,
LastVoteOn datetime default '0000-00-00' NOT NULL,
UNIQUE(WordText)
)CHARACTER SET utf8 collate utf8_turkish_ci;


CREATE TABLE IF NOT EXISTS Plays(
UserID bigint NOT NULL,
SetID bigint NOT NULL,
Vote1 tinyint DEFAULT -1 NOT NULL,
Vote2 tinyint DEFAULT -1 NOT NULL,
Vote3 tinyint DEFAULT -1 NOT NULL,
Vote4 tinyint DEFAULT -1 NOT NULL,
Vote5 tinyint DEFAULT -1 NOT NULL,
Vote6 tinyint DEFAULT -1 NOT NULL,
Vote7 tinyint DEFAULT -1 NOT NULL,
Vote8 tinyint DEFAULT -1 NOT NULL,
Vote9 tinyint DEFAULT -1 NOT NULL,
Vote10 tinyint DEFAULT -1 NOT NULL,
Word1 bigint DEFAULT 1 NOT NULL,
Word2 bigint DEFAULT 1 NOT NULL,
Word3 bigint DEFAULT 1 NOT NULL,
Word4 bigint DEFAULT 1 NOT NULL,
Word5 bigint DEFAULT 1 NOT NULL,
Word6 bigint DEFAULT 1 NOT NULL,
Word7 bigint DEFAULT 1 NOT NULL,
Word8 bigint DEFAULT 1 NOT NULL,
Word9 bigint DEFAULT 1 NOT NULL,
Word10 bigint DEFAULT 1 NOT NULL,
EndPoint int DEFAULT 0 NOT NULL,
BonusPoint int DEFAULT 0 NOT NULL,
MatchPoint int DEFAULT NULL,
MatchWith int DEFAULT 0 NOT NULL,
PRIMARY KEY(UserID,SetID),
FOREIGN KEY(UserID)
	REFERENCES Users(UserID)
	ON UPDATE CASCADE,
FOREIGN KEY(SetID)
	REFERENCES Sets(SetID)
	ON UPDATE CASCADE,
FOREIGN KEY(Word1)
	REFERENCES Words(WordID)
	ON UPDATE CASCADE,
FOREIGN KEY(Word2)
	REFERENCES Words(WordID)
	ON UPDATE CASCADE,
FOREIGN KEY(Word3)
	REFERENCES Words(WordID)
	ON UPDATE CASCADE,
FOREIGN KEY(Word4)
	REFERENCES Words(WordID)
	ON UPDATE CASCADE,
FOREIGN KEY(Word5)
	REFERENCES Words(WordID)
	ON UPDATE CASCADE,
FOREIGN KEY(Word6)
	REFERENCES Words(WordID)
	ON UPDATE CASCADE,
FOREIGN KEY(Word7)
	REFERENCES Words(WordID)
	ON UPDATE CASCADE,
FOREIGN KEY(Word8)
	REFERENCES Words(WordID)
	ON UPDATE CASCADE,
FOREIGN KEY(Word9)
	REFERENCES Words(WordID)
	ON UPDATE CASCADE,
FOREIGN KEY(Word10)
	REFERENCES Words(WordID)
	ON UPDATE CASCADE
)CHARACTER SET utf8 collate utf8_turkish_ci;

CREATE TABLE IF NOT EXISTS Followers(
FollowerID bigint NOT NULL,
FollowedID bigint NOT NULL,
FOREIGN KEY(FollowedID)
	REFERENCES Users(UserID)
	ON UPDATE CASCADE,
PRIMARY KEY(FollowerID,FollowedID)
)

INSERT INTO Users VALUES (0,"NA","NA","NA",0,0,NOW(),'0000-00-00',0);
INSERT INTO Words VALUES (0,"NA",0,0,0,0,0,NOW(),NOW());
INSERT INTO Tweets VALUES (0,0,"NA",NOW(),NOW(),0,0);
