SET @TUTORIALID = (SELECT SetID FROM Plays ORDER BY Rand() LIMIT 1);

SELECT ROUND(AVG(Vote1)) AS Vote1, ROUND(AVG(Vote2)) AS Vote2, ROUND(AVG(Vote3)) AS Vote3, ROUND(AVG(Vote4)) AS Vote4, ROUND(AVG(Vote5)) AS Vote5, ROUND(AVG(Vote6)) AS Vote6, ROUND(AVG(Vote7)) AS Vote7, ROUND(AVG(Vote8)) AS Vote8, ROUND(AVG(Vote9)) AS Vote9, ROUND(AVG(Vote10)) AS Vote10, COUNT(*),SetID FROM Plays WHERE SetID = @TUTORIALID AND Vote1!=-1 AND Vote2!=-1 AND Vote3!=-1 AND Vote4!=-1 AND Vote5!=-1 AND Vote6!=-1 AND Vote7!=-1 AND Vote8!=-1 AND Vote9!=-1 AND Vote10!=-1;

SELECT Word1, COUNT(*) AS magnitude 
FROM Plays WHERE SetID=@TUTORIALID
GROUP BY Word1 
ORDER BY magnitude DESC LIMIT 1;

SELECT Word2, COUNT(*) AS magnitude 
FROM Plays WHERE SetID=@TUTORIALID
GROUP BY Word2 
ORDER BY magnitude DESC LIMIT 1;

SELECT Word3, COUNT(*) AS magnitude 
FROM Plays WHERE SetID=@TUTORIALID
GROUP BY Word3 
ORDER BY magnitude DESC LIMIT 1;

SELECT Word4, COUNT(*) AS magnitude 
FROM Plays WHERE SetID=@TUTORIALID
GROUP BY Word4 
ORDER BY magnitude DESC LIMIT 1;

SELECT Word5, COUNT(*) AS magnitude 
FROM Plays WHERE SetID=@TUTORIALID
GROUP BY Word5 
ORDER BY magnitude DESC LIMIT 1;

SELECT Word6, COUNT(*) AS magnitude 
FROM Plays WHERE SetID=@TUTORIALID
GROUP BY Word6 
ORDER BY magnitude DESC LIMIT 1;

SELECT Word7, COUNT(*) AS magnitude 
FROM Plays WHERE SetID=@TUTORIALID
GROUP BY Word7 
ORDER BY magnitude DESC LIMIT 1;

SELECT Word8, COUNT(*) AS magnitude 
FROM Plays WHERE SetID=@TUTORIALID
GROUP BY Word8
ORDER BY magnitude DESC LIMIT 1;

SELECT Word9, COUNT(*) AS magnitude 
FROM Plays WHERE SetID=@TUTORIALID
GROUP BY Word9 
ORDER BY magnitude DESC LIMIT 1;

SELECT Word10, COUNT(*) AS magnitude 
FROM Plays WHERE SetID=@TUTORIALID
GROUP BY Word10 
ORDER BY magnitude DESC LIMIT 1;